### ISSUE TITLE
`set-output` is deprecated and needs replacing

### ISSUE THREAD

**Issue by timberhill** [timberhill/container-image-tag-action#19]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

New way of doing this:

```yaml
- name: Save state
  run: echo "{name}={value}" >> $GITHUB_STATE

- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT
```

```bash
echo "::set-output name=image-tag::$prefix$new_tag"
echo "image-tag=$prefix$new_tag" >> $GITHUB_OUTPUT
```
